

* Easy :
- Hide next link in HTML source code
- Have text be the same color as background to make it visible only by highlighting
- Putting an emphasis (bold, different color, different font) on some random letters on story to form a word or a code
- Java Calculator project hidden in a comment in the HTML source code
- Putting hidden text in the trailer/teaser/the BwB socials
- Encrypting clues using Binary Hexadecimal Base64 Caesar ASCII..etc
- Hidden text using Morse (either using images. videos, or audio)
- MD5 Hashing
* Medium :
- Putting a sequence of letters and numbers that are actually a link to a pastebin document https://pastebin.com/<SECRET_CODE> .
- Same thing but with https://youtube.com/watch?v=<SECRET_CODE> .
- If possible use the newly made Cherry-Crystal https://crystal.tilde.institute/blog/c/cherry.html (Pretty pleaaaase).
- Playing with file formats like hiding informations in PNGs and JPEGs using Steganography.
- Using Playing cards like tarrot cards and Pocker sets to convey a hidden meaning.

* Hard :
- Having random numbers form GEOGRAPHIC coordinates that point to a specific place either for more lore. or for a code.
- Hidding text in the hexcode of a program/dll.
- Requiring to reverse engineer/decode a program (either in java or assembly) to get a secret code.
- Increasing saturation in some illustrations to reveal hidden text.
- Having to manipulate an image in a certain way to make it make sense (inverting colors, changing the shape...etc)
- Having to use an SSTV software to get some pictures. Example : https://www.n8mdp.com/sstv.php
