* Initial :

Lore :


A series of Strange disappearances happened in the town of XY, so an investigator decides to Investigate about it. He quickly comes to the observation that they all share one common Symbol ungraved on the walls of the disappearances places. Tragically this investigator meets the same faith because of this entity, leaving behind him 3 years of documented work, and 4 children. 4 children that will go and investigate about the mysterious murder of their dad, using what their father left them as "unfinished documentation"

Déroulement:
+The player gets to choose a character from the 4 children which all have their own "style of engimas", as they each look in different places. but their paths intersect at some points in the story (though briefly). And each one of them will finally discover the identity of the murderer which will be the end of the event...Or maybe not on ferra en sorte que pour avoir la vrai vrai fin, il faut jouer les 4 personnages un aprés l'autre pour avoir un code secret et débloquer le reste du lore+

One path, 4 children, the player goes back and forth between the pov of the children investigating

Enigmas will vary from decoding the corrupted documents of their dad, deciphering ancient documents and digging through the traces of the entity

As for the Entity herself, we will make her an Inter-dimensional entity, genre qui se déplace entre la réalité normale et la réalité online (d'ou les indices en ligne)



Relation with the Name "Echoes":
The victims of the disappearances will surface from time to time Online either helping the player, give them more lore, or even give cryptic hints.

* Okay Ines's take :

Instead of having random strange disappearances , we will have this : The father is part of a research team that are working on a microship that breaks the walls between the Internet reality and the Real life. Sadly something comes out from the internet, a manifestation of the collective consciousness of  Internet-users and their deranged ideas(?), which starts making the research team disappear one by one, leaving a single Logo on the place of their disappearance and making them "Echoes", just voices roaming the Internet grieving about something (probably le3jouv qu'ils ont vu online) causing glitches, random gibberish and breakage all over the net. The Father tries to investigate what happened, but he also disappears and becomes an Echo himself. et voila ses enfants sont inquétés et ils vont investiger la disaparition et blabla c'est la méme que l'histoire en haut.


WOOHOOOOOO : *Approved By Gaya !!!*
